
baseURL = "https://spuit.12px.com/"
languageCode = "ja"
title = "Spuit"
theme = "spuit"
copyright = "🍄"

archetypeDir = "site/archetypes"
assetDir = "site/assets"
contentDir = "site/content"
dataDir = "site/data"
layoutDir = "site/layouts"
publishDir = "public"
staticDir = "site/static"
themesDir = "site/themes"

pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "monokai"
pygmentsUseClasses = true
pygmentsoptions = "linenos=inline"

[params]
description = "description"
keywords = "keywords"
googleAnalyticsId = ""
fbAppId = ""

[permalinks]
post = "/:year/:month/:title/"

[taxonomies]
tag = "tags"
category = "categories"
